# Generated by Django 6.1.1 on 2026-09-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('bom_reference', models.CharField(blank=True, max_length=255)),
                ('purl', models.TextField(blank=True)),
                ('external_references', models.TextField(blank=True)),
                ('lang', models.CharField(blank=True, max_length=100)),
                ('attack_surface', models.CharField(blank=True, max_length=50)),
                ('security_function', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
